version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "spruce-bruce"

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/api"
    schedule:
      interval: "daily"
    reviewers:
      - "spruce-bruce"

  # Maintain dependencies for Composer
  - package-ecosystem: "npm"
    directory: "/e2e"
    schedule:
      interval: "daily"
    reviewers:
      - "spruce-bruce"

