version: "3"

services:
  api:
    build:
        context: .
        dockerfile: ./api/Dockerfile
        args:
            PACKAGE_PATH: ./api
            WORKING_DIR: /src/api
    environment:
      - OIDC_DB_ADAPTER=postgresql
      - OIDC_DB_USER=postgres
      - OIDC_DB_PASSWORD=root
      - OIDC_DB_NAME=postgres
      - OIDC_DB_HOST=postgres
      - OIDC_DB_PORT=5432
    env_file:
        - ./common.env
    volumes:
        - .:/src
        - ./redis/tls:/usr/local/etc/redis/tls
    depends_on:
        - postgres
        - redis
    entrypoint: ./wait-for-it.sh -t 0 postgres:5432 --
    command: ["npm", "run", "start-dev"]
  redis:
    image: redis
    command: ["/app/redis/docker-redis-entrypoint.sh"]
    ports:
      - 6379:6379
      - 6380:6380
    volumes:
      - ./:/app
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/tls:/usr/local/etc/redis/tls
